typedef struct {
	BOOL itemIsEnabled[25];
	char timeString[64];
	int gsmSignalStrengthRaw;
	int gsmSignalStrengthBars;
	char serviceString[100];
	char serviceCrossfadeString[100];
	char serviceImages[2][100];
	char operatorDirectory[1024];
	unsigned serviceContentType;
	int wifiSignalStrengthRaw;
	int wifiSignalStrengthBars;
	unsigned dataNetworkType;
	int batteryCapacity;
	unsigned batteryState;
	char batteryDetailString[150];
	int bluetoothBatteryCapacity;
	int thermalColor;
	unsigned thermalSunlightMode : 1;
	unsigned slowActivity : 1;
	unsigned syncActivity : 1;
	char activityDisplayId[256];
	unsigned bluetoothConnected : 1;
	unsigned displayRawGSMSignal : 1;
	unsigned displayRawWifiSignal : 1;
	unsigned locationIconType : 1;
	unsigned quietModeInactive : 1;
	unsigned tetheringConnectionCount;
} StatusBarData_iOS7;

@interface SBStatusBarStateAggregator : NSObject {
	unsigned _coalescentBlockDepth;
	BOOL _hasPostedOnce;
	unsigned _itemPostState[25];
	BOOL _nonItemDataChanged;
	StatusBarData_iOS7 _data;
	int _actions;
	NSHashTable* _postObservers;
	BOOL _notifyingPostObservers;
	NSDateFormatter* _timeItemDateFormatter;
	NSTimer* _timeItemTimer;
	NSString* _timeItemTimeString;
	NSString* _operatorName;
	NSString* _serviceString;
	NSString* _serviceCrossfadeString;
	NSArray* _countryCodesShowingEmergencyOnlyStatus;
	BOOL _showsActivityIndicatorOnHomeScreen;
	int _activityIndicatorEverywhereCount;
	BOOL _showsActivityIndicatorForNewsstand;
	int _syncActivityIndicatorCount;
	NSString* _activityDisplayIdentifier;
	BOOL _showingNotChargingItem;
	NSString* _batteryDetailString;
	BOOL _alarmEnabled;
	BOOL _applyingAssistantStyle;
}
+(int)_thermalColorForLevel:(int)level;
+(id)sharedInstance;
-(void)_noteNotChargingStatusChanged;
-(void)_setShowingNotChargingItem;
-(BOOL)_shouldShowNotChargingItem;
-(BOOL)_shouldShowEmergencyOnlyStatus;
-(id)_sbCarrierNameForOperator:(id)anOperator;
-(id)_displayStringForRegistrationStatus:(int)registrationStatus;
-(id)_displayStringForSIMStatus:(id)simstatus;
-(BOOL)_simStatusMeansLocked:(id)locked;
-(void)_noteAirplaneModeChanged;
-(void)_resetTimeItemFormatter;
-(void)_restartTimeItemTimer;
-(void)_stopTimeItemTimer;
-(void)_requestActions:(int)actions;
-(void)_notifyNonItemDataChanged;
-(void)_notifyItemChanged:(int)changed;
-(BOOL)_setItem:(int)item enabled:(BOOL)enabled;
-(void)_postItem:(int)item withState:(unsigned)state;
-(void)updateStatusBarItem:(int)item;
-(void)_updateTetheringState;
-(void)_updateThermalColorItem;
-(void)_updateAssistantItem;
-(void)_updateAirplayItem;
-(void)_updateQuietModeItem;
-(void)_updateRotationLockItem;
-(void)_updateLocationItem;
-(void)_updateActivityItem;
-(void)_updateCallForwardingItem;
-(void)_updateVPNItem;
-(void)_updateAlarmItem;
-(void)_updateTTYItem;
-(void)_updateBluetoothBatteryItem;
-(void)_updateBluetoothItem;
-(void)_updateBatteryItems;
-(void)_updateDataNetworkItem;
-(void)_updateServiceItem;
-(void)_updateSignalStrengthItem;
-(void)_updateAirplaneMode;
-(void)_updateTimeItems;
-(void)_registerForNotifications;
-(void)removePostingObserver:(id)observer;
-(void)addPostingObserver:(id)observer;
-(void)sendStatusBarActions:(int)actions;
-(void)setShowsSyncActivityIndicator:(BOOL)indicator;
-(void)setShowsActivityIndicatorForNewsstand:(BOOL)newsstand;
-(void)setShowsActivityIndicatorEverywhere:(BOOL)everywhere;
-(void)setShowsActivityIndicatorOnHomeScreen:(BOOL)screen;
-(void)setAlarmEnabled:(BOOL)enabled;
-(id)operatorName;
-(void)endCoalescentBlock;
-(void)beginCoalescentBlock;
-(void)dealloc;
-(id)init;
@end

